### ISSUE TITLE
Tiny Toon Adventures - Buster's Hidden Treasure (USA) has no title screen music

### ISSUE THREAD

**Issue by therealinfidelity** [SmokeMonsterPacks/Mega-Sg-Jailbreak#77] opened 2020-05-25 01:32 UTC
Using the latest firmware available as of 5-24-20, using the latest firmware on my Mega Everdrive X7, when loading the USA version of Tiny Tune Adventures, the title screen music does not play. It is not an issue with my rom or my Everdrive, since the cartridge & rom play the title screen music on my VA6 model 1 Genesis, and my VA2 model 2 Genesis.

**Comment by tjanas** [comment] 2020-05-25 02:36
I have confirmed this bug exists with loading the no-intro rom via the latest jailbreak firmware.

**Comment by shroom2k** [comment] 2020-06-13 22:38
I can confirm that I also have the same bug.

**Comment by BooBerry** [comment] 2021-02-22 19:55
With the new official v4.,8 firmware release, I can confirm this issue still exists.

P.S. It probably would've been helpful to clarify that it's **Tiny Toon Adventures - Buster's Hidden Treasure (USA)** with the broken title screen music as the other Tiny Toon game **Tiny Toon Adventures - ACME All-Stars (USA, Korea)** works fine.

**Comment by therealinfidelity** [comment] 2021-02-22 21:35
> With the new official v4.,8 firmware release, I can confirm this issue still exists.
> 
> P.S. It probably would've been helpful to clarify that it's **Tiny Toon Adventures - Buster's Hidden Treasure (USA)** with the broken title screen music as the other Tiny Toon game **Tiny Toon Adventures - ACME All-Stars (USA, Korea)** works fine.

Sorry. :-/

**Comment by BooBerry** [comment] 2021-02-24 19:43
It's quite alright, and I did ask kevtris about this in the Classic Gaming Discord channel and he's aware of the issue and looked into it but couldn't figure out why it happens yet. So it's on his known issues radar and hopefully he can figure it out when he gets the time to work on it again. :)

**Comment by tjanas** [comment] 2021-02-24 20:38
Apparently the issue is not present on the Genesis core for Mister, maybe some insight could be gained it?

**Comment by AydanWatkins** [comment] 2021-02-25 17:17
The game DOES have title screen music for me, I played it using an original cartridge using firmware v4.8 from Analogue. I know this is the Jailbreak firmware GitHub but surely if it works on official it should work on the Jailbreak firmware when updated too right?

**Comment by BooBerry** [comment] 2021-02-25 17:19
And you're playing `Tiny Toon Adventures - Buster's Hidden Treasure (USA)` right? `Tiny Toon Adventures - ACME All-Stars (USA, Korea)` works fine with the title screen music fortunately.

**Comment by AydanWatkins** [comment] 2021-02-25 17:21
Mine was Tiny Toon Adventures - Buster's Hidden Treasure (PAL) using an original official Megadrive cartridge. Surely it can't be down to Region??? If it plays on PAL it should on USA right? o_O

**Comment by BooBerry** [comment] 2021-02-25 18:17
Yes, it's a region difference. The EU PAL version works with music in the title screen, the US NTSC version does not.

**Comment by PizzaCube** [comment] 2021-05-06 22:48
it does not play on a real cart either.

**Comment by tjanas** [comment] 2023-05-05 10:52
@therealinfidelity @BooBerry @shroom2k @PizzaCube can you please re-test with the new official firmware update? https://www.analogue.co/support/mega-sg/firmware/4.9

**Comment by BooBerry** [comment] 2023-05-06 13:27
Yes, this issue is now fixed.

**Closed** 2023-05-06 13:36 UTC
Labels: bug, valid ROM, needs verification
