### ISSUE TITLE
Not able to load alternate Mega-CD firmware on 7.5

### ISSUE THREAD

**Issue by ChronoStriker1** [SmokeMonsterPacks/Mega-Sg-Jailbreak#39] opened 2019-06-12 00:18 UTC
**Describe the bug**
Unable to load alternative Mega-CD bios

**To Reproduce**
    Make sure the auto region detection is turned on in the hardware menu
    Check the option to use a replacement CD BIOS
    Select a replacement BIOS loaded on your SD card
    Save your settings.
    Run cartridge

**Expected behavior**
Mega-CD loads with alternative bios

**Firmware version**
JB7.5

**Comment by frederic-mahe** [comment] 2019-06-12 11:10
@ChronoStriker1 do you confirm that you were able to load the same alternative bios with JBv7.4?

**Comment by ChronoStriker1** [comment] 2019-06-12 12:07
Yes, and I can confirm if I downgrade back to JBv7.4 the settings works as expected.

**Comment by alexcom84** [comment] 2019-06-12 12:13
I confirm that loading an alternate bios won’t work on my model 1. If someone could test on their SegaCD to rule out it is not affecting only the JPN units.

**Comment by frederic-mahe** [comment] 2019-06-12 17:51
is this linked to issue #34 ?

**Comment by alexcom84** [comment] 2019-06-12 18:43
Another user confirmed this issue on the atariage thread on a NA model 2, so it’s not related only to the jpn units.
  
It’s kinda different because the alternate bios would not run at all, where in previous issue the problem was only happening on next power on. As someone else mentioned, on jb 7.4 you were able to bypass the issue by selecting the genesis core then back to main menu and “Run cartridge”.

**Comment by bumfacekilla** [comment] 2019-06-13 21:17
I have the same issue using a PAL Mega CD 2, worked fine on JB7.4 aside from needing to enter and exit the Genesis core to get it to kick in.

**Comment by TheRealFlamepanther** [comment] 2019-06-14 04:57
The old behavior was that after reboot, the alternate BIOS wouldn't be loaded until after the Genesis core had been triggered, either by running a cartridge (or CD) or by entering Cores>>Genesis and backing out. The new 7.5 behavior is that the alternate BIOS doesn't load **at all** whatsoever. It's completely broken.

US Sega CD 2.

**Comment by BarbieOnWeed** [comment] 2019-08-10 14:33
> 
> 
> Another user confirmed this issue on the atariage thread on a NA model 2, so it’s not related only to the jpn units.
> 
> It’s kinda different because the alternate bios would not run at all, where in previous issue the problem was only happening on next power on. As someone else mentioned, on jb 7.4 you were able to bypass the issue by selecting the genesis core then back to main menu and “Run cartridge”.

This is what you have to do even on the new 7.6 version.

**Comment by SmokeMonsterPacks** [comment] 2019-11-19 23:17
This should be fixed in the latest JB update. I will re-open this if not.

**Closed by SmokeMonsterPacks** 2019-11-19 23:17 UTC
Labels: bug, regression

**Comment by ChronoStriker1** [comment] 2019-11-20 01:38
I can confirm that they do indeed load but due to timing issues all bios's tested crash.
