### ISSUE TITLE
Sega CD - Vay - Blue Screen During Intro

### ISSUE THREAD

**Issue by FrJosh** [SmokeMonsterPacks/Mega-Sg-Jailbreak#22] opened 2019-04-17 04:58 UTC
## Expected behavior and actual behavior
When starting a new game the screen turns blue during the intro and a short section of the audio (the guy talking to you) keeps repeating over and over.

## Steps to reproduce the problem
Just start a new game and watch the intro

Firmware: 7.4

**Comment by jairulnait** [comment] 2019-04-17 05:01
I experienced the same issue. Model 2 SCD and JB7.4.

**Comment by GreatHierophant** [comment] 2019-04-17 05:37
Ditto

**Comment by BooBerry** [comment] 2019-06-10 10:02
This issue has been fixed in the official 4.5 firmware.

https://support.analogue.co/hc/en-us/articles/360024836892-Mega-Sg-Firmware-Update-v4-5

**Comment by alexcom84** [comment] 2019-06-10 20:35
Tested and working as intended on fw 4.5.

**Comment by frederic-mahe** [comment] 2019-06-12 11:08
It should also be fixed in the jailbreak firmware. @alexcom84 it would be great if you could make the test.

**Comment by alexcom84** [comment] 2019-06-12 12:05
Working well on jb 7.5 !

**Closed** 2019-06-12 17:41 UTC
Labels: bug, original cartridge or CD, regression
